# Generated by Django 5.0.2 on 2024-02-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
